name: 🎉 Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Set Timezone
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          echo "Asia/Shanghai" | sudo tee /etc/timezone
          date
        shell: bash

      - name: Build
        run: pnpm run build

      - name: Set npmrc for client
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > packages/client/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set npmrc for icons
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > packages/icons/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set npmrc for server
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >  packages/server/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set npmrc for shared
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > packages/shared/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set npmrc for utils-client
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > packages/utils/client/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set npmrc for utils-server
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > packages/utils/server/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: pnpm run publish:script

      - run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
